# This is a basic workflow to help you get started with Actions

name: publish-stage

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: /src

    - name: Checkout destination repository
      uses: actions/checkout@v4
      with:
        repository: groupdocs/reference.groupdocs.com
        path: /dest
        ref: main
        token: ${{ secrets.REPO_TOKEN }}
        fetch-depth: 1

    - name: Sync files to destination (exclude LICENSE, README.md, .github)
      run: |
        rsync -a --delete \
          --exclude 'LICENSE' \
          --exclude 'README.md' \
          --exclude '.github/' \
          /src/ /dest/content/sites/groupdocs/markdown/

    - name: Commit and push changes
      working-directory: /dest
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit."
          exit 0
        fi
        git commit -m "chore: sync markdown files from source repo"
        git push origin main